target-version = "py38"
line-length = 120

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "YTT", # flake8-2020
    "S",   # bandit (security)
    "BLE", # flake8-blind-except
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "C4",  # flake8-comprehensions
    "T10", # flake8-debugger
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PL",  # pylint
    "TRY", # tryceratops
    "RUF", # ruff-specific rules
]
ignore = [
    "S101",   # assert (allow assert statements in tests)
    "T201",   # print (allow print statements)
    "B008",   # function-call-in-default-argument
    "PLR0913", # too-many-arguments
    "PLR0912", # too-many-branches
    "TRY003",  # raise-vanilla-args
    "TRY300",  # try-consider-else (stylistic preference)
    "TRY301",  # raise-within-try (simple validation checks don't need abstraction)
    "S603",    # subprocess-without-shell-equals-true
    "S607",    # start-process-with-partial-path
]

[lint.per-file-ignores]
"tests/*" = [
    "S101", # assert
    "PLR2004", # magic-value-comparison
    "ARG001", # unused-function-argument
]
