name: cproj
type: tool
features:
  claude_workspace: true      # Setup .claude directory with commands/agents
  claude_symlink: true        # Create .cursorrules symlink to CLAUDE.md
  review_agents: true         # Enable automated review agents
  nvm_setup: true             # Create setup-claude.sh for Node integration
  env_sync_check: true        # Check for env file changes during review
  auto_terminal: false        # We launch via rc + osascript instead

custom_actions:
  # Launch remote-claude session in Terminal
  - type: run_command
    description: Launch remote-claude session with Terminal
    command: |
      osascript -e 'tell application "Terminal" to do script "rc start {worktree_path} --name {worktree_name}"'
